---
name: "AMI-build1"
on:
  push:
    branches:
      - main
jobs:
  AMI-build2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        with:
          version: "latest"
      - name: Packer Init
        run: packer init ./packer/main.pkr.hcl
      - name: Packer validate
        run: packer validate ./packer/main.pkr.hcl
      - name: Packer Build
        run: packer build ./packer/main.pkr.hcl
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_KEY}}
          AWS_REGION: ap-southeast-2
